language: generic 
sudo: required

services: 
  - docker

before_install: 
  -  docker build -t basov/docker-complex-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true basov/docker-complex-frontend npm test:unit

after_success: 
  - docker build basov/docker-complex-frontend ./frontend
  - docker build basov/docker-complex-nginx ./nginx
  - docker build basov/docker-complex-api ./api
  - docker build basov/docker-complex-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push basov/docker-complex-frontend
  - docker push basov/docker-complex-nginx
  - docker push basov/docker-complex-api
  - docker push basov/docker-complex-worker