language: generic 
sudo: required

services: 
  - docker

before_install: 
  -  docker build -t basov/docker-complex-frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true basov/docker-complex-frontend npm run test:unit

after_success: 
  - docker build -t basov/docker-complex-frontend ./frontend
  - docker build -t basov/docker-complex-ngnix ./ngnix
  - docker build -t basov/docker-complex-api ./api
  - docker build -t basov/docker-complex-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push basov/docker-complex-frontend
  - docker push basov/docker-complex-ngnix
  - docker push basov/docker-complex-api
  - docker push basov/docker-complex-worker

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "eu-central-1"
  app: "docker-complex"
  env: "DockerComplex-env"
  bucket_name: "elasticbeanstalk-eu-central-1-160682765790"
  bucket_path: "docker-complex"
  on:
    branch: master