version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  ngnix:
    depends_on: 
      - api
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./ngnix
    ports: 
      - '8080:80'
  api:
    depends_on: 
      - postgres
      - redis
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    volumes: 
      - /app/node_modules
      - ./api:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_PASSWORD=postgres_password
      - PG_DATABASE=postgres
      - PG_HOST=postgres
      - PG_PORT=5432
  frontend: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /app/node_modules
      - ./frontend:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379